ci: fix backport workflow

diff --git a/.github/workflows/backport.yml b/.github/workflows/backport.yml
--- a/.github/workflows/backport.yml
+++ b/.github/workflows/backport.yml
@@ -26,7 +26,7 @@ jobs:
         run: |
           git config user.name "ornladios-robot"
           git config user.email "ornladios-robot[bot]@users.noreply.github.com"
-          git remote set fork "https://github.com/ornladios-robot/ADIOS2.git"
+          git remote add fork "https://github.com/ornladios-robot/ADIOS2.git"
       - name: Create backport
         env:
           GH_TOKEN: ${{ secrets.BACKPORT_TOKEN }}
@@ -35,7 +35,11 @@ jobs:
           export PR=${{ github.event.inputs.pr }}
           git checkout --track "origin/${BRANCH}"
           git checkout -b "backport-to-${BRANCH}-${PR}"
-          commit_hash=$(gh pr view --json mergeCommit --jq '.mergeCommit.oid' "${PR}")
+          commit_hash=$(gh pr view "${PR}" --repo ornladios/ADIOS2 --json mergeCommit --jq '.mergeCommit.oid')
+          if [ -z "$commit_hash" ] || [ "$commit_hash" = "null" ]; then
+            echo "Error: PR ${PR} is not merged yet"
+            exit 1
+          fi
           git cherry-pick --mainline 1 -x "${commit_hash}"
           git push -f fork "backport-to-${BRANCH}-${PR}"
-          gh pr create --base "${BRANCH}" --title "Backport ${PR} to ${BRANCH}" --body "backports: ${PR}"
+          gh pr create --repo ornladios/ADIOS2 --head ornladios-robot:backport-to-${BRANCH}-${PR} --base "${BRANCH}" --title "Backport ${PR} to ${BRANCH}" --body "backports: ${PR}"
